apiVersion: v1
kind: Secret
metadata:
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:
  password: cGFzc3....   # Put Your Password In Base64
  username: ....W4=  # Put Your Password In Base64
